In [1]:
import numpy as np
import pandas as pd

In [15]:
# Creation aleatoire d'objet

labels=['a', 'b', 'c']
mylist=[10, 20, 30]

#tableau numpy
arr=np.array([10, 20, 30])

#dictionnaire
d={'A':10, 'B':20, 'C':30}

# ci dessus, ce trouve nos 4 objets classique python.
# On va essayer de les convertis en objet serie pandas

In [16]:
# Conversion d'objet classique en series pandas
#
# pd.Series(data='notre donnee', index='par defaut commence a la position 0')

# pd.Series(data=labels) or pd.Series(labels)
# pd.Series(data=arr) or pd.Series(labels)

pd.Series(data=mylist)

0    10
1    20
2    30
dtype: int64

In [17]:
# On peut preciser l'indexe(nom de l'indexe), en utilisant un autre objet de meme taille mais pas forcement de meme type

pd.Series(data=mylist, index=labels)

pd.Series(mylist, labels)

a    10
b    20
c    30
dtype: int64

In [18]:
# Ca fonctionne egalement avec les tableaux NumPy

pd.Series(arr, mylist)
# 10    10
# 20    20
# 30    30
# dtype: int64

pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [20]:
#dictionnaire : pandas ordonne normalement notre dictionnaire
# d={'a':10, 'b':20, 'c':30}

pd.Series(d, mylist) # index non correspondant aux données
# 10   NaN
# 20   NaN
# 30   NaN
# dtype: float64

pd.Series(d)

A    10
B    20
C    30
dtype: int64

In [32]:
# On crée une nouvelle Series.
# Elle list et etiquette les prix des ventes(sales) du 1er trimestre( Quater 1) en fonction des pays

# En gros, il s'agit du montant des ventes de differents pays sur le premier trimestre

sales_Q1=pd.Series(data=[250, 450, 200, 150], index=['USA', 'China', 'India', 'Brazil'])
sales_Q1

USA       250
China     450
India     200
Brazil    150
dtype: int64

In [30]:
# Nouvelle serie du meme genre

sales_Q2=pd.Series([260, 500, 360, 145], ['USA', 'China', 'India', 'Japan'])
sales_Q2

USA      260
China    500
India    360
Japan    145
dtype: int64

In [34]:
# Si je veux la vente de China(dans Q1) par exemple, il me suffit de l'appeler( un peu comme avec les dico clé-valeur)

sales_Q1['China']

450

In [35]:
# Si on le voulait dans Q2

sales_Q2['China']

500

In [39]:
# On peut trouver un element via son indexe(commence toujours à l'index 0)
#
# USA      260 [index 0]
# China    500 [index 1]
# India    360 [index 2]
# Japan    145 [index 3]
#
# Quand on ajoute l'indexe, alors c'est l'index qui s'affiche et non la données

sales_Q2[0] #-->260
sales_Q2[2] # sales_Q2['India']

360

In [40]:
sales_Q2['Japan'] # sales_Q2[3]

145

In [44]:
# On peut effectuer des operations sur les Series
#
# Par exemple on peut aditionner nos 2 series, pour les memes index, on aura la somme des data.
# si les indexes sont differents, alors on aura un NaN(Not a Number), pour dire non def

sumQ1_Q2=sales_Q1+sales_Q2
sumQ1_Q2

# Brazil garde sa valeurs unique, il ne peut etre additionné, et c'est pareil pour Japan
# Plutard on saura comment conserver dans notre sortie les vrais valeur de nos indexes a la place du NaN

Brazil      NaN
China     950.0
India     560.0
Japan       NaN
USA       510.0
dtype: float64

In [45]:
time_Q1_Q2=sales_Q1*sales_Q2
time_Q1_Q2

Brazil         NaN
China     225000.0
India      72000.0
Japan          NaN
USA        65000.0
dtype: float64

In [46]:
rst=2*sales_Q2
rst

USA       520
China    1000
India     720
Japan     290
dtype: int64

In [47]:
sumG=2*sumQ1_Q2
sumG

Brazil       NaN
China     1900.0
India     1120.0
Japan        NaN
USA       1020.0
dtype: float64